# Generated by Django 4.1.3 on 2024-02-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Stash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=25)),
                ('last_name', models.CharField(default=None, max_length=25)),
                ('uid', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storystashapi.book')),
                ('stash', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storystashapi.stash')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storystashapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='stash',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storystashapi.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storystashapi.genre'),
        ),
    ]
