# Generated by Django 4.2.7 on 2024-02-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storystashapi', '0003_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stashbook',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
