# Generated by Django 4.2.7 on 2024-03-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storystashapi', '0004_stashbook_isread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storystashapi.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storystashapi.user')),
            ],
        ),
    ]
